CREATE DATABASE auth_db;
CREATE DATABASE user_db;
CREATE DATABASE account_db;
CREATE DATABASE transaction_db;
CREATE DATABASE creditcard_db;
CREATE DATABASE loan_db;
CREATE DATABASE document_db;
CREATE DATABASE notification_db;
CREATE DATABASE admin_db;

GRANT ALL PRIVILEGES ON DATABASE auth_db TO bank;
GRANT ALL PRIVILEGES ON DATABASE user_db TO bank;
GRANT ALL PRIVILEGES ON DATABASE account_db TO bank;
GRANT ALL PRIVILEGES ON DATABASE transaction_db TO bank;
GRANT ALL PRIVILEGES ON DATABASE creditcard_db TO bank;
GRANT ALL PRIVILEGES ON DATABASE loan_db TO bank;
GRANT ALL PRIVILEGES ON DATABASE document_db TO bank;
GRANT ALL PRIVILEGES ON DATABASE notification_db TO bank;
GRANT ALL PRIVILEGES ON DATABASE admin_db TO bank;
