apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: banking
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - infra.yaml
  - document-pvc.yaml
  - app-services.yaml
