apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: banking
data:
  init-databases.sql: |
    CREATE DATABASE auth_db;
    CREATE DATABASE user_db;
    CREATE DATABASE account_db;
    CREATE DATABASE transaction_db;
    CREATE DATABASE creditcard_db;
    CREATE DATABASE loan_db;
    CREATE DATABASE document_db;
    CREATE DATABASE notification_db;
    CREATE DATABASE admin_db;

    GRANT ALL PRIVILEGES ON DATABASE auth_db TO bank;
    GRANT ALL PRIVILEGES ON DATABASE user_db TO bank;
    GRANT ALL PRIVILEGES ON DATABASE account_db TO bank;
    GRANT ALL PRIVILEGES ON DATABASE transaction_db TO bank;
    GRANT ALL PRIVILEGES ON DATABASE creditcard_db TO bank;
    GRANT ALL PRIVILEGES ON DATABASE loan_db TO bank;
    GRANT ALL PRIVILEGES ON DATABASE document_db TO bank;
    GRANT ALL PRIVILEGES ON DATABASE notification_db TO bank;
    GRANT ALL PRIVILEGES ON DATABASE admin_db TO bank;
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: banking
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: banking
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: banking-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: banking-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: postgres
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "bank"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
      volumes:
        - name: init
          configMap:
            name: postgres-init
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
