apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: ConfigMap
      name: banking-config
    patch: |
      - op: replace
        path: /data/DEPLOYMENT_ENVIRONMENT
        value: banking-app
      - op: replace
        path: /data/OTEL_RESOURCE_ATTRIBUTES
        value: deployment.environment.name=banking-app,deployment.environment=banking-app,service.namespace=securebank,demo.name=banking-platform
